/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 01-abr.-2020 3:28:22 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Deporte CASCADE
;

DROP TABLE IF EXISTS Deportista CASCADE
;

DROP TABLE IF EXISTS Ganadores CASCADE
;

DROP TABLE IF EXISTS Lugar CASCADE
;

DROP TABLE IF EXISTS Tiempo CASCADE
;

/* Create Tables */

CREATE TABLE Deporte
(
	n_nombre varchar(100) NOT NULL,
	k_id_deporte integer NOT NULL
)
;

CREATE TABLE Deportista
(
	n_nombre varchar(200) NOT NULL,
	k_id_dep integer NOT NULL,
	v_edad integer NOT NULL,
	n_sexo varchar(1) NOT NULL
)
;

CREATE TABLE Ganadores
(
	n_medallas varchar(50) NULL,
	k_id_medallas varchar(50) NOT NULL,
	k_secuencia integer NOT NULL,
	k_id_deporte integer NOT NULL,
	k_id_lugar integer NOT NULL,
	k_id_dep integer NOT NULL
)
;

CREATE TABLE Lugar
(
	n_ciudad varchar(50) NOT NULL,
	k_id_lugar integer NOT NULL
)
;

CREATE TABLE Tiempo
(
	n_decada integer NOT NULL,
	n_quinquenio integer NOT NULL,
	n_trienio integer NOT NULL,
	"n_año" integer NOT NULL,
	k_secuencia integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Deporte ADD CONSTRAINT PK_Deporte
	PRIMARY KEY (k_id_deporte)
;

ALTER TABLE Deportista ADD CONSTRAINT PK_Deportista
	PRIMARY KEY (k_id_dep)
;

ALTER TABLE Ganadores ADD CONSTRAINT PK_Ganadores
	PRIMARY KEY (k_id_medallas)
;

CREATE INDEX IXFK_Ganadores_Deporte ON Ganadores (k_id_deporte ASC)
;

CREATE INDEX IXFK_Ganadores_Deportista ON Ganadores (k_id_dep ASC)
;

CREATE INDEX IXFK_Ganadores_Lugar ON Ganadores (k_id_lugar ASC)
;

CREATE INDEX IXFK_Ganadores_Tiempo ON Ganadores (k_secuencia ASC)
;

ALTER TABLE Lugar ADD CONSTRAINT PK_Lugar
	PRIMARY KEY (k_id_lugar)
;

ALTER TABLE Tiempo ADD CONSTRAINT PK_Tiempo
	PRIMARY KEY (k_secuencia)
;

/* Create Foreign Key Constraints */

ALTER TABLE Ganadores ADD CONSTRAINT FK_Ganadores_Deporte
	FOREIGN KEY (k_id_deporte) REFERENCES Deporte (k_id_deporte) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Ganadores ADD CONSTRAINT FK_Ganadores_Lugar
	FOREIGN KEY (k_id_lugar) REFERENCES Lugar (k_id_lugar) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Ganadores ADD CONSTRAINT FK_Ganadores_Tiempo
	FOREIGN KEY (k_secuencia) REFERENCES Tiempo (k_secuencia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Ganadores ADD CONSTRAINT fk_id_dep
	FOREIGN KEY (k_id_dep) REFERENCES Deportista (k_id_dep) ON DELETE No Action ON UPDATE No Action
;
